STATE_DICT_NAME = 'model_state_dict'
ARTIFACT_LOG_PRIORS_NAME = 'artifact_log_priors'
ARTIFACT_SPECTRA_STATE_DICT_NAME = 'artifact_spectra_state_dict'
M3_PARAMS_NAME = 'm3_params'
NUM_READ_FEATURES_NAME = 'num_read_features'
NUM_INFO_FEATURES_NAME = 'num_info_features'
REF_SEQUENCE_LENGTH_NAME = 'ref_sequence_length'
HIDDEN_LAYERS_NAME = 'hidden_layers'

INPUT_NAME = 'input'
OUTPUT_NAME = 'output'
ARTIFACT_POSTERIOR_OUTPUT_NAME = 'artifact_posterior_output'
OUTPUT_DIR_NAME = 'output_dir'

READ_EMBEDDING_DIMENSION_NAME = 'read_embedding_dimension'
NUM_TRANSFORMER_HEADS_NAME = 'num_transformer_heads'
TRANSFORMER_HIDDEN_DIMENSION_NAME = 'transformer_hidden_dimension'
NUM_TRANSFORMER_LAYERS_NAME = 'num_transformer_layers'

INFO_LAYERS_NAME = 'info_layers'
AGGREGATION_LAYERS_NAME = 'aggregation_layers'
REF_SEQ_LAYER_STRINGS_NAME = 'ref_seq_layer_strings'
DROPOUT_P_NAME = 'dropout_p'
LEARNING_RATE_NAME = 'learning_rate'
BATCH_NORMALIZE_NAME = 'batch_normalize'
LEARN_ARTIFACT_SPECTRA_NAME = 'learn_artifact_spectra'

TRAINING_DATASETS_NAME = 'training_datasets'
TRAIN_TAR_NAME = 'train_tar'
ARTIFACT_TAR_NAME = 'artifact_tar'
TEST_DATASET_NAME = 'test_dataset'
NORMAL_ARTIFACT_DATASETS_NAME = 'normal_artifact_datasets'
REWEIGHTING_RANGE_NAME = 'reweighting_range'
BATCH_SIZE_NAME = 'batch_size'
CHUNK_SIZE_NAME = 'chunk_size'
NUM_EPOCHS_NAME = 'num_epochs'
NUM_WORKERS_NAME = 'num_workers'
NUM_SPECTRUM_ITERATIONS = 'num_spectrum_iterations'

TENSORBOARD_DIR_NAME = 'tensorboard_dir'

INITIAL_LOG_VARIANT_PRIOR_NAME = 'initial_log_variant_prior'
INITIAL_LOG_ARTIFACT_PRIOR_NAME = 'initial_log_artifact_prior'
GENOMIC_SPAN_NAME = 'genomic_span'
MAF_SEGMENTS_NAME = 'maf_segments'
NORMAL_MAF_SEGMENTS_NAME = 'normal_maf_segments'
GERMLINE_MODE_NAME = 'germline_mode'
NO_GERMLINE_MODE_NAME = 'no_germline_mode'

M3_MODEL_NAME = 'm3_model'
